name: Caller Job
on:
  workflow_dispatch:

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.find-dev-branches.outputs.branches }}
    steps:
      - name: Checkout branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set branches
        id: find-dev-branches
        run: |
          git fetch --all
          BRANCHES=$( git branch -r | grep -v HEAD | grep "origin/dev/" | sed "s/origin\///" | sed "s/ //g")
          echo $BRANCHES
          branch_array=$(printf "%s" "${BRANCHES[@]}" | jq -R . | jq -s . | jq -c)
          echo $branch_array
          echo "branches=$branch_array" >> "$GITHUB_OUTPUT"
          branches=$branch_array
          echo $branches
  test:
    runs-on: ubuntu-latest
    needs: set-matrix
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(needs.set-matrix.outputs.branches) }}
    steps:
      - name: print branch
        run: |
          echo ${{matrix.branch}}
          echo ${{github.run_id}}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{matrix.branch}}
      - name: create PR
        run: |
          export BRANCH_NAME="github-actions-test/${{matrix.branch}}__${{github.run_id}}"
          git switch $BRANCH_NAME
