name: Caller Job
on:
  workflow_dispatch:

jobs:
  steps:
    strategy:
      fail-fast: true
      max-parallel: 2
      matrix:
        node:
          - test1
          - test2
          - test3
          - test4
          - test5
          - test6
          - test7
    name: 同時実行

    uses: ./.github/workflows/callee.yml
    with:
      name: ${{ matrix.node }}

    # runs-on:
    #   with: sanro
    # with:
    #   name: sanro
