name: Caller Job
on:
  workflow_dispatch:

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/callee.yml
    with:
      name: taro

  call_reusable_workflow2:
    uses: ./.github/workflows/callee.yml
    with:
      name: jiro

  steps:
    uses: ./.github/workflows/callee.yml
    with:
      name: sanro
