name: Caller Job
on:
  workflow_dispatch:

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.find-dev-branches.outputs.branches }}
    steps:
      - name: Checkout branches
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set branches
        id: find-dev-branches
        run: |
          git fetch --all
          BRANCHES=$( git branch -r )
          echo $BRANCHES

  # steps:
  #   name: 同時実行
  #   strategy:
  #     fail-fast: false
  #     max-parallel: 2
  #     matrix:
  #       node:
  #         - test1
  #         - test2
  #         - test3
  #         - test4
  #         - test5
  #         - test6
  #         - test7
  #   uses: ./.github/workflows/callee.yml
  #   with:
  #     name: ${{ matrix.node }}

  # runs-on:
  #   with: sanro
  # with:
  #   name: sanro
