name: Caller Job
on:
  workflow_dispatch:

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/callee.yml
    with:
      name: taro

  call_reusable_workflow2:
    uses: ./.github/workflows/callee.yml
    with:
      name: jiro

  steps:
    strategy:
      fail-fast: false
      matrix:
        node: [test1, test2, test3]
    uses: ./.github/workflows/callee.yml
    with:
      name: ${{ matrix.node }}

    # runs-on:
    #   with: sanro
    # with:
    #   name: sanro
